<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ti</groupId>
        <artifactId>ti_live_app</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>ti-live-order</artifactId>
    <packaging>pom</packaging>
    <name>ti-live-order</name>
    <description>订单支付服务模块</description>

    <modules>
        <module>ti-live-order-interface</module>
        <module>ti-live-order-provider</module>
    </modules>

</project>
